// Orebody offline cache. Generated by tools/build_present.py.
const CACHE='orebody-v0dd02f6459';
self.addEventListener('install',e=>{self.skipWaiting();});
self.addEventListener('activate',e=>{e.waitUntil(
  caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k))))
    .then(()=>self.clients.claim()));});
self.addEventListener('fetch',e=>{
  const r=e.request;
  if(r.method!=='GET') return;
  const url=new URL(r.url);
  // Terrain and imagery tiles are unbounded; cache only what has been seen.
  e.respondWith(caches.match(r).then(hit=>{
    if(hit) return hit;
    return fetch(r).then(res=>{
      if(res && (res.status===200||res.type==='opaque')){
        const copy=res.clone();
        caches.open(CACHE).then(c=>c.put(r,copy)).catch(()=>{});
      }
      return res;
    }).catch(()=>hit);
  }));
});
self.addEventListener('message',e=>{
  if(e.data==='usage'){
    caches.open(CACHE).then(c=>c.keys()).then(ks=>{
      e.source.postMessage({cached:ks.length});});
  }
});
