// Orebody offline cache. Generated by tools/build_present.py.
const CACHE='orebody-v436ef112d6';
self.addEventListener('install',e=>{self.skipWaiting();});
self.addEventListener('activate',e=>{e.waitUntil(
  caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k))))
    .then(()=>self.clients.claim()));});
// Tiles are effectively unbounded, so the cache is capped and trimmed FIFO.
// Opaque responses are NOT cached: their status is always 0, so an opaque 404
// would be stored as a permanent success that can never be corrected, and they
// are padding-inflated against the storage quota.
const MAX_ENTRIES=1200;
let writes=0;
async function trim(){
  const c=await caches.open(CACHE);
  const ks=await c.keys();
  if(ks.length<=MAX_ENTRIES) return;
  for(const k of ks.slice(0, ks.length-MAX_ENTRIES)) await c.delete(k);
}
self.addEventListener('fetch',e=>{
  const r=e.request;
  if(r.method!=='GET') return;
  e.respondWith(caches.match(r).then(hit=>{
    if(hit) return hit;
    return fetch(r).then(res=>{
      if(res && res.status===200 && res.type!=='opaque'){
        const copy=res.clone();
        caches.open(CACHE).then(c=>c.put(r,copy)).then(()=>{
          if(++writes%200===0) return trim();
        }).catch(()=>{});
      }
      return res;
    }).catch(()=>hit);
  }));
});
self.addEventListener('message',e=>{
  if(e.data==='usage'){
    caches.open(CACHE).then(c=>c.keys()).then(ks=>{
      e.source.postMessage({cached:ks.length});});
  }
});
