// Orebody offline cache. Generated by tools/build_present.py.
const CACHE='orebody-vf0b086ffd2';
self.addEventListener('install',e=>{self.skipWaiting();});
self.addEventListener('activate',e=>{e.waitUntil(
  caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k))))
    .then(()=>self.clients.claim()));});
// Tiles are effectively unbounded, so the cache is capped and trimmed FIFO.
// Opaque responses are NOT cached: their status is always 0, so an opaque 404
// would be stored as a permanent success that can never be corrected, and they
// are padding-inflated against the storage quota.
const MAX_ENTRIES=1200;
let writes=0;
async function trim(){
  const c=await caches.open(CACHE);
  const ks=await c.keys();
  if(ks.length<=MAX_ENTRIES) return;
  for(const k of ks.slice(0, ks.length-MAX_ENTRIES)) await c.delete(k);
}
// What this cache must NOT touch.
//
// The worker is registered at the site root, so its scope is everything —
// including the authoring console at /dashboard/ and every API call the console
// makes. Cache-first over that scope is actively harmful: the console would
// serve users the JavaScript from whichever deploy they first visited, forever,
// and authenticated Supabase GETs would be stored and replayed as though the
// data had never changed. Tiles are the only thing here worth caching
// aggressively, so everything else is passed straight to the network.
function bypass(r){
  const u=new URL(r.url);
  if(u.origin===location.origin && u.pathname.startsWith('/dashboard/')) return true;
  // Supabase (or any) API surface — data, auth and edge functions.
  if(/\/(rest|auth|functions|storage)\/v\d/.test(u.pathname)) return true;
  // Anything carrying credentials is per-user and must never be shared.
  if(r.headers.get('authorization')||r.headers.get('apikey')) return true;
  return false;
}
self.addEventListener('fetch',e=>{
  const r=e.request;
  if(r.method!=='GET') return;
  if(bypass(r)) return;
  // The DOCUMENT is network-first. Everything else here can be cache-first
  // because it is immutable per build, but the page itself is the build, and
  // cache-first on it meant a returning visitor ran the previous deploy until
  // the new worker had activated AND they had loaded again — two reloads to
  // see a fix, with no way to tell which one you were looking at. On a tool
  // that quotes tonnage that is not a caching strategy, it is a correctness
  // bug. Offline still works: the cached copy is the fallback, not the
  // default.
  if(r.mode==='navigate'||(r.destination==='document')){
    e.respondWith(
      fetch(r).then(res=>{
        if(res&&res.status===200&&res.type!=='opaque'){
          const copy=res.clone();
          caches.open(CACHE).then(c=>c.put(r,copy)).catch(()=>{});
        }
        return res;
      }).catch(()=>caches.match(r).then(hit=>hit||caches.match('index.html'))));
    return;
  }
  e.respondWith(caches.match(r).then(hit=>{
    if(hit) return hit;
    return fetch(r).then(res=>{
      if(res && res.status===200 && res.type!=='opaque'){
        const copy=res.clone();
        caches.open(CACHE).then(c=>c.put(r,copy)).then(()=>{
          if(++writes%200===0) return trim();
        }).catch(()=>{});
      }
      return res;
    }).catch(()=>hit);
  }));
});
self.addEventListener('message',e=>{
  if(e.data==='usage'){
    caches.open(CACHE).then(c=>c.keys()).then(ks=>{
      e.source.postMessage({cached:ks.length});});
  }
});
